Modified castle architecture to fit the new problem specifications.
kelzuriel/SamuraiAndTheLabyrinth pull request #1
Opened 2017-01-11 16:03 UTC by kelzuriel

Modified castle architecture to fit the new problem specifications. Updated starting location.

2017-01-19 09:00 UTC, kelzuriel commented on theMind.js
> +var castle = new Array(3);
Changed number of lines from 10 to 3.

2017-01-19 09:00 UTC, kelzuriel commented on theMind.js
> +castle[1][1] = "Samurai";
Changed Samurai and Katana position.

2017-01-19 09:00 UTC, kelzuriel commented on theMind.js
> +castle[0][0] = "Wall";
Changed walls pattern.

2017-01-19 09:00 UTC, kelzuriel commented on theMind.js
> +  if(dfl < 0 || dfl >= 10 || dft < 0 || dft >= 3) {
Changed search limits from 10 up to down, and 10 right toleft, to 3 up todown, and 10 right to left.

2017-01-19 09:00 UTC, kelzuriel commented on theMind.js
> +  if(dfl < 0 || dfl >= 10 || dft < 0 || dft >= 3) {
Irina: What is a castle?

2017-01-19 09:00 UTC, kelzuriel commented on theMind.js
> +console.log(calculateShortestPath([1,1], castle));
Changed starting location.

2017-01-19 09:05 UTC, kelzuriel commented on theMind.js
> +var castle = new Array(3);
DRY line and column number should only be changed in one place.

2017-01-19 09:06 UTC, kelzuriel commented on theMind.js
> +castle[1][1] = "Samurai";
DRY Samurai position should only be changed in one place.

2017-01-26 09:28 UTC, dira requested changes

2017-01-26 09:28 UTC, dira commented on theMind.js
> +var lineNumber = 3;
numărul cărei linii este ăsta?

2017-01-26 10:28 UTC, merged